accordion/urls.py
from django.urls import path

from . import views

app_name = 'accordion'

urlpatterns = [
    path('accordion', views.accordion, name='accordion'),
]

ajax/urls.py
from django.urls import path

from . import views

app_name = 'ajax'

urlpatterns = [
    path('book', views.halaman, name='halaman'),
    path('dataBuku', views.dataBuku),
]

cookie/urls.py
from django.urls import path
from . import views

app_name = 'cookie'

urlpatterns = [
    path('login', views.login_user , name ='login'),
    path('', views.loginFinish , name ='loginFinish'),
    path('logout', views.logout_user, name='logout'),
    path('signup', views.signup, name='signup'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

yukbisa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('accordion.urls')),
    path('', include('ajax.urls')),
    path('', include('cookie.urls')),
]

accordion/models.py
from django.db import models

# Create your models here.

ajax/models.py
from django.db import models

# Create your models here.

cookie/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

accordion/views.py
from django.shortcuts import render

# Create your views here.
def accordion(request):
    return render(request, 'accordionpage.html')

ajax/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.http import HttpResponse
import requests

# Create your views here.
def halaman(request):
    return render(request,'book.html')

def dataBuku(request):
    key = request.GET['key']
    url = 'https://www.googleapis.com/books/v1/volumes?q=' + key
    response = requests.get(url)
    response_json = response.json()

    return JsonResponse(response_json)

cookie/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django.urls import reverse


# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'index.html')
    else:
        form = UserCreationForm()

    form = UserCreationForm()

    return render(request, 'signup.html', { 'form':form })


def login_user(request):
    response = {}
    if request.method == "POST":
        user_id = request.POST['user_id']
        password = request.POST['password']
        user = authenticate(request, username=user_id, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('cookie:loginFinish'))
        else:
            response["user_not_found"]= "User is doesn't exist"
            return render(request, 'login.html', response) 
            # HttpResponse("Username and Password is not created")
    else:         
        return render(request,'login.html',response)

def loginFinish(request):
    response = {}
    response['user'] = request.user
    return render(request, 'index.html', response)

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('home:index'))

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

accordion/templates/accordionpage.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'accord.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <title>Accordion</title>
  </head>


<body>
    <div class="accord">
        <div class="container">
          <div class="jumbotron">
            <h2 style="color: #fbf7f5; font-size: 40px; font-weight: 400; text-align: center;" >My Story Line</h2>
          </div>
                <div class="panel-group" id="accordion">
                    <div class="panel">
                        <div class="panel-heading">
                            <span class = "pull-right">
                                <div class="accordion-buttons col-2 d-flex justify-content-flex">
                                  <div class="button-up">
                                      <button type="button" id="button-up" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-up"></button>
                                  </div>
                                  <div class="button-down">
                                      <button type="button" id="button-down" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-down"></button>
                                  </div>
                                </div>
                              </span>
                          <h4 class="panel-title">
                              <button class="btn" style="color:#675c52; background: transparent;" type="button" data-parent=#accordion data-toggle="collapse"
                              data-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                              <strong>Education</strong>
                            </button>
                          </h4>
                        </div>
                        <div id="collapse1" class="panel-collapse collapse">
                          <div class="panel-body">
                            <ul>
                                Universitas Indonesia : 2019 - present <br>
                                SMAN 3 Kota Tangerang Selatan : 2016 - 2019 <br>
                                SMPN 11 Kota Tangerang Selatan : 2013 -  2016<br>
                                SDN PUSPIPTEK : 2007 - 2013
                            </ul>
                          </div>
                        </div>
                      </div>
                      <div class="panel">
                          <div class="panel-heading">
                              <span class = "pull-right">
                                  <div class="accordion-buttons col-2 d-flex justify-content-flex">
                                      <div class="button-up">
                                          <button type="button" id="button-up" data-parent=#accordion class="btn btn-default glyphicon glyphicon-chevron-up"></button>
                                      </div>
                                      <div class="button-down">
                                          <button type="button" id="button-down" data-parent=#accordion class="btn btn-default glyphicon glyphicon-chevron-down"></button>
                                      </div>
                                    </div>
                                </span>
                            <h4 class="panel-title">
                                <button class="btn" style="color: #675c52; background: transparent;"  type="button" data-parent=#accordion data-toggle="collapse"
                                data-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                <strong>Experience</strong>
                              </button>
                            </h4>
                          </div>
                          <div id="collapse2" class="panel-collapse collapse">
                            <div class="panel-body">
                                <ul>
                                    Person in Charge of Event OH Fasilkom 2020<br>
                                    Staff of Digital Marketing COMPFEST 12<br>
                                    Staff of Liaison Officer Wisuda Ganjil 2019 <br>
                                    Staff of Public Relation OH Fasilkom 2019<br>
                                </ul>
                            </div>
                          </div>
                        </div>
                  <div class="panel">
                    <div class="panel-heading">
                        <span class = "pull-right">
                            <div class="accordion-buttons col-2 d-flex justify-content-flex">
                                <div class="button-up">
                                    <button type="button" id="button-up" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-up"></button>
                                </div>
                                <div class="button-down">
                                    <button type="button" id="button-down" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-down"></button>
                                </div>
                              </div>
                          </span>
                      <h4 class="panel-title">
                          <button class="btn" style="color:#675c52; background: transparent;"  type="button" data-parent=#accordion data-toggle="collapse"
                          data-target="#collapse3" aria-expanded="false" aria-controls="collapse3">
                          <strong> Hobby </strong>
                        </button>
                      </h4>
                    </div>
                    <div id="collapse3" class="panel-collapse collapse">
                      <div class="panel-body">
                        <ul>
                            Organize stuff<br>
                            Travelling<br>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="panel">
                    <div class="panel-heading">
                        <span class = "pull-right">
                            <div class="accordion-buttons col-2 d-flex justify-content-flex">
                                <div class="button-up">
                                    <button type="button" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-up"></button>
                                </div>
                                <div class="button-down">
                                    <button type="button" data-parent=#accordion class="btn btn-default up glyphicon glyphicon-chevron-down"></button>
                                </div>
                              </div>
                          </span>
                      <h4 class="panel-title">
                          <button class="btn" style="color: #675c52; background: transparent;"  type="button" data-parent=#accordion data-toggle="collapse"
                          data-target="#collapse4" aria-expanded="false" aria-controls="collapse4">
                          <strong> Contact </strong>
                        </button>
                      </h4>
                    </div>
                    <div id="collapse4" class="panel-collapse collapse">
                      <div class="panel-body">
                        <ul>
                            Instagram : keikoaaliya <br>
                            Twitter : keikoaaliya <br>
                            Line : keikoahp <br>
                        </ul>
                      </div>
                    </div>
                  </div> 
                </div>
                
                </div>
    </div>
              

              <script src="{% static 'accord.js' %}"></script>
</body>
</html>

ajax/templates/book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/styleBook.css'%}">
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    <!-- <script src="{% static '/js/bbb.js' %}"></script> -->
    <link href="https://fonts.googleapis.com/css?family=Oswald|Quicksand&display=swap" rel="stylesheet">
    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            crossorigin="anonymous"></script>
    <title>Book</title>
</head>
<style>
    body {
        margin: 0;
        padding: 0;
        text-align: center;
        background-color: #fbf7f5;
    }
    button{
        border-radius: 5px;
        background-color: none;
        color: black ;
        border: 1.5px solid black;
    }
    button:hover{
        background-color:#f9e1e0 !important ;
    }
    .buat-table #ini{
        margin-right: auto;
        margin-left: auto;
    }
    td {
        padding-top: 10px;
        padding-bottom: 10px;
        padding-right: 10px;
        padding-left: 10px;
    }
    #data {
        text-align: left;
    }
</style>
<body>
    <div class="abc">
        <p class="h1" style="margin-top: 5vw;"> Find Your Favorite Book!</p>
        <input id="search" type="text" class="mt-3" placeholder="Search Book here!"  style="width: 13vw; font-family: 'Quicksand';">
        <!-- <button style="font-family: 'Quicksand', sans-serif; background-color: floralwhite;" class="ml-2" id="button">Submit</button> -->
        <button id="button">Submit</button>
    </div>

    <div class="buat-table" style="padding-top: 30px;">
        <table id="ini" border="1" style="width: 70%; justify-content: center;">
            <!-- Buat Ajax  -->
        </table>
    </div>
   
    <script>
    $('#button').click(function() {
        event.preventDefault();
        const key = $('#search').val();
        $.ajax({
            method: 'GET',
            url: '/dataBuku?key='+key,
            success: function (result){
                let booksView = $('#ini');
                booksView.empty();
                const resultList = result.items;
                for(let i = 0; i< resultList.length; i++){
                    let book = resultList[i].volumeInfo;
                    console.log(book)
                    booksView.append(
                        '<tr><th>No<th>Cover</th><th>Description</th>' +
                        '<tr><td>' + (i+1) + '</td><td><img src=' + 
                            book.imageLinks.smallThumbnail + '></td>' +
                            '<td id="data"><strong>Title: </strong><a href="' + book.previewLink + '">' + book.title + '</a><br>' +
                            '<strong>Category: </strong>' + book.categories + '</a><br>' +
                            '<strong>Author: </strong>' + book.authors + '</a><br>' +
                            '<strong>Published Date: </strong>' + book.publishedDate + '</a><br>' +
                            '<strong>Publisher: </strong>' + book.publisher + '</a><br></td><tr>'
                    );
                }
            }
        });
    });
    </script>
</body>
</html>

cookie/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static '/css/styleBook.css'%}">
    
    <script src="{% static '/js/bbb.js' %}"></script> -->
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Oswald|Quicksand&display=swap" rel="stylesheet">
    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            crossorigin="anonymous"></script>
    <title>Login</title>
</head>
<body>
    <div style="text-align: center;" class="status">
        <p class="h1" style="text-align: center;">Login</p>
    
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-2">
                <input type="user_id" name="user_id" id="user_id" placeholder="Username" required>
            </div>
            <div>
                <input type="password" name="password" id="password" placeholder="Password" required>
            </div>
                <p>
                    {{user_not_found}}
                </p>
            <button class="btn-secondary" id="login_button">Sign in</button>
            
        </form>
    </div>

</body>
</html>

cookie/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static '/css/styleBook.css'%}">
    <link rel="stylesheet" href="{% static '/css/style.css'%}"> -->
    <!-- <script src="{% static '/js/bbb.js' %}"></script> -->
    <link href="https://fonts.googleapis.com/css?family=Oswald|Quicksand&display=swap" rel="stylesheet">
    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            crossorigin="anonymous"></script>
    <title>Signup</title>
</head>
<body>
    <h1>Sign Up</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Sign Up</button>
    </form>
</body>
</html>

home/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Yuk Bisa</title>
{% endblock meta %}

{% block content %}
<div class="home">
    {% include 'navbar.html' %}
    <div class="text" style="text-align: center;">
        {% if user.is_authenticated %}
        <h2>Hi {{user.username}} Selamat Datang di Website Ini</h2>
        {% else %}
        <h2>Login untuk dapatkan fitur terbaik</h2>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Stencil+Display&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Nunito&display=swap" rel="stylesheet">
    {% block meta %}
    {% endblock meta %}
</head>

<body>
    {% block content %}
    {% endblock content %}

    {% block script %}
    {% endblock script %}
</body>

</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg" style="background-color: #675c52">
    <a class="navbar-brand" href="#">
        <div class ="title">
            keiko.
        </div>
    </a>
    <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'home:index' %}">
                    <div class ="navbar-item-text">
                        Home 
                    </div>
                    <span class="sr-only">
                        (current)
                    </span>
                </a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'accordion:accordion' %}">
                    <div class ="navbar-item-text">
                        Accordion
                    </div>
                </a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'ajax:halaman' %}">
                    <div class ="navbar-item-text">
                        Book
                    </div>
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'cookie:logout' %}">
                    <div class ="navbar-item-text">
                        Logout
                    </div>
                </a>
            </li>
            {% else %}
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'cookie:login' %}">
                    <div class ="navbar-item-text">
                        Login
                    </div>
                </a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'cookie:signup' %}">
                    <div class ="navbar-item-text">
                        Sign Up
                    </div>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>